name: ccy-helper

on:
  schedule:
    - cron: "00 06 * * *" # 每天的6点执行一次、国际标准时间

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run Project
        run: npm install && npm run server
