name: ccy-helper

on:
  schedule:
    - cron: "0 0 16 * *" # 每天的0点、8点、12点、21点都执行一次

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run Project
        run: npm install && npm run server
